---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-service
  namespace: speedtest
spec:
  selector:
    app: speedtest
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
  type: LoadBalancer # This makes it accessible on localhost for Docker Desktop
